import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { FaBolt, FaVolumeUp, FaShieldAlt, FaCheckCircle, FaExclamationTriangle, FaChartLine } from "react-icons/fa";
import { useBill } from "../context/BillContext";
import { getBillHealth, scenarioEstimate } from "../utils/billHealthEngine";

const COPY = {
  en: { title: "Bill Health Check", subtitle: "A plain-language check of your bill. This is not appliance detection or an exact prediction.", listen: "Listen", confidence: "Confidence", scenarios: "Plan next month", upload: "Upload a bill", action: "Best next action", normal: "Normal use", high: "More AC / guests", away: "Away from home" },
  hi: { title: "बिल हेल्थ चेक", subtitle: "अपने बिजली बिल को आसान भाषा में समझें। यह उपकरणों की पहचान या सटीक भविष्यवाणी नहीं है।", listen: "सुनें", confidence: "विश्वास स्तर", scenarios: "अगले महीने की योजना", upload: "बिल अपलोड करें", action: "अगला सही कदम", normal: "सामान्य उपयोग", high: "एसी / मेहमान अधिक", away: "घर से बाहर" },
  mr: { title: "बिल हेल्थ चेक", subtitle: "तुमचे वीज बिल सोप्या भाषेत समजून घ्या. हे उपकरण ओळखणे किंवा अचूक अंदाज नाही.", listen: "ऐका", confidence: "विश्वास पातळी", scenarios: "पुढील महिन्याची योजना", upload: "बिल अपलोड करा", action: "पुढची योग्य कृती", normal: "नेहमीचा वापर", high: "एसी / पाहुणे अधिक", away: "घरापासून दूर" },
};
const scenarioOptions = [{ key: "normal", delta: 0 }, { key: "high", delta: 20 }, { key: "away", delta: -70 }];

export default function BillHealthPage() {
  const { bills } = useBill(); const [lang, setLang] = useState("en"); const [scenario, setScenario] = useState("normal");
  const health = useMemo(() => getBillHealth(bills), [bills]); const t = COPY[lang];
  const selected = scenarioOptions.find((item) => item.key === scenario);
  const estimate = health ? scenarioEstimate(health, selected.delta) : null;
  function speak() { if (!health || !window.speechSynthesis) return; const message = lang === "hi" ? `इस महीने आपने ${health.units} यूनिट बिजली का उपयोग किया। आपका बिल ${health.amount} रुपये है।` : lang === "mr" ? `या महिन्यात तुम्ही ${health.units} युनिट वीज वापरली. तुमचे बिल ${health.amount} रुपये आहे.` : `This month you used ${health.units} units. Your bill is ${health.amount} rupees. ${health.findings[0].text}`; const utterance = new SpeechSynthesisUtterance(message); utterance.lang = lang === "hi" ? "hi-IN" : lang === "mr" ? "mr-IN" : "en-IN"; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); }
  if (!health) return <div className="space-y-6"><section className="bill-health-hero"><FaShieldAlt/><div><h1>{t.title}</h1><p>{t.subtitle}</p></div></section><div className="bg-white rounded-2xl p-10 text-center border border-amber-100"><FaBolt className="text-amber text-3xl mx-auto mb-4"/><h2 className="font-bold text-xl">Start with one bill</h2><p className="text-slate mt-2 mb-5">Upload a bill to receive a clear explanation in your chosen language.</p><Link to="/bills/upload" className="inline-block bg-amber px-5 py-2.5 rounded-lg font-semibold text-navy">{t.upload}</Link></div></div>;
  return <div className="space-y-6">
    <section className="bill-health-hero"><FaShieldAlt/><div><p className="text-xs uppercase tracking-widest text-amber-100 font-semibold">PowerPulse bill copilot</p><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="ml-auto flex gap-2 flex-wrap"><select aria-label="Language" value={lang} onChange={(e)=>setLang(e.target.value)} className="rounded-lg px-3 py-2 text-sm text-gray-800"><option value="en">English</option><option value="hi">हिंदी</option><option value="mr">मराठी</option></select><button onClick={speak} className="rounded-lg bg-amber px-3 py-2 text-sm font-semibold text-navy flex items-center gap-2"><FaVolumeUp/>{t.listen}</button></div></section>
    <div className="grid md:grid-cols-3 gap-4"><Metric icon={<FaBolt/>} label="Units used" value={`${health.units} kWh`}/><Metric icon={<FaChartLine/>} label="Bill amount" value={`₹${health.amount.toLocaleString("en-IN")}`}/><Metric icon={<FaShieldAlt/>} label={t.confidence} value={health.confidence} note="Based only on uploaded bill history"/></div>
    <div className="grid lg:grid-cols-5 gap-6"><section className="lg:col-span-3 bg-white border border-gray-200 rounded-2xl p-6"><h2 className="font-bold text-xl text-gray-900">What changed?</h2><p className="text-sm text-gray-500 mt-1">We show evidence from your bill—not guessed appliance readings.</p><div className="mt-5 space-y-3">{health.findings.map((finding) => <div key={finding.title} className={`rounded-xl p-4 bill-finding-${finding.tone}`}><div className="flex gap-3"><span className="mt-0.5">{finding.tone === "teal" ? <FaCheckCircle/> : <FaExclamationTriangle/>}</span><div><h3 className="font-semibold">{finding.title}</h3><p className="text-sm mt-1">{finding.text}</p></div></div></div>)}</div><div className="mt-6 rounded-xl bg-amber-50 border border-amber-100 p-4"><p className="font-semibold text-amber-900">{t.action}</p><p className="text-sm text-amber-900 mt-1">{health.units > 300 ? "Avoid extra use during the rest of the billing cycle: each new unit costs the higher marginal rate. Enter a meter reading in Slab Jump Guard for a daily target." : "Compare this bill with the same season next year before deciding an appliance is faulty."}</p></div></section>
      <section className="lg:col-span-2 bg-white border border-gray-200 rounded-2xl p-6"><h2 className="font-bold text-xl">{t.scenarios}</h2><p className="text-sm text-gray-500 mt-1">A range for a chosen situation, not a promise.</p><div className="mt-4 space-y-2">{scenarioOptions.map((item)=><button key={item.key} onClick={()=>setScenario(item.key)} className={`w-full text-left rounded-xl border p-3 text-sm font-medium ${scenario===item.key ? "border-amber bg-amber-50 text-amber-900" : "border-gray-200 text-gray-700 hover:bg-gray-50"}`}>{t[item.key]}</button>)}</div><div className="mt-5 rounded-xl bg-teal-50 p-4"><p className="text-sm text-teal-800">Expected range</p><p className="text-2xl font-bold text-teal-800 mt-1">₹{estimate.low.toLocaleString("en-IN")} – ₹{estimate.high.toLocaleString("en-IN")}</p><p className="text-sm text-teal-800 mt-1">Around {estimate.units} units, assuming this scenario.</p></div></section></div>
    <p className="text-xs text-gray-500 px-1">Transparent limits: PowerPulse cannot determine appliance-level consumption from a monthly bill. Scenarios use your latest bill and illustrative slab rates; weather, occupancy, meter timing, tariff charges, and changed habits can alter the actual result.</p>
  </div>;
}

function Metric({ icon, label, value, note }) { return <div className="bg-white rounded-2xl border border-gray-200 p-5"><div className="w-9 h-9 rounded-lg bg-amber-50 text-amber-700 flex items-center justify-center">{icon}</div><p className="text-sm text-gray-500 mt-4">{label}</p><p className="font-bold text-xl text-gray-900 capitalize mt-1">{value}</p>{note && <p className="text-xs text-gray-400 mt-1">{note}</p>}</div>; }
