import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { billForUnits } from "../utils/slabRates";

const input = "mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400";
const money = (v) => `₹${Math.round(v).toLocaleString("en-IN")}`;
function NumberField({ label, value, onChange, min = 0, step = 1 }) { return <label className="text-sm text-gray-600">{label}<input className={input} type="number" min={min} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
function Card({ title, description, children }) { return <section className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm"><h2 className="text-xl font-bold text-gray-900">{title}</h2><p className="text-sm text-gray-500 mt-1 mb-5">{description}</p>{children}</section>; }

export default function EnergyToolsPage() {
  const [bill, setBill] = useState({ units: 340, days: 38, charged: 3900, fac: 0.35, duty: 0.16 });
  const [load, setLoad] = useState({ sanctioned: 5, peak: 2, fixedRate: 110 });
  const [tod, setTod] = useState({ solar: 70, peak: 90, flexible: 45, rebate: 0.8, surcharge: 0.18, rate: 8 });
  const [solar, setSolar] = useState({ units: 450, roof: 500, rate: 8, loanRate: 8 });
  const [replacement, setReplacement] = useState({ type: "AC", age: 10, star: 3, inverter: false, price: 42000, rate: 8 });
  const audit = useMemo(() => { const cycle = Math.max(bill.days, 1); const prorated = billForUnits(bill.units * 30 / cycle) * cycle / 30; const expected = prorated + bill.units * (bill.fac + bill.duty); return { expected, gap: bill.charged - expected }; }, [bill]);
  const loadSavings = Math.max(0, (load.sanctioned - Math.max(1, Math.ceil(load.peak + 0.5))) * load.fixedRate);
  const todSavings = Math.max(0, tod.flexible * (tod.rate * tod.surcharge + tod.rebate));
  const solarResult = useMemo(() => { const capacity = Math.min(Math.max(1, Math.ceil(solar.units / 120)), Math.max(1, Math.floor(solar.roof / 100))); const cost = capacity * 60000; const subsidy = capacity >= 3 ? 78000 : capacity === 2 ? 60000 : 30000; const netOutlay = cost - subsidy; const monthly = Math.min(solar.units, capacity * 120) * solar.rate; const r = solar.loanRate / 1200; const emi = netOutlay * r * Math.pow(1 + r, 60) / (Math.pow(1 + r, 60) - 1); return { capacity, cost, subsidy, netOutlay, monthly, emi, payback: Math.ceil(netOutlay / Math.max(monthly, 1)) }; }, [solar]);
  const replacementResult = useMemo(() => { const oldBase = replacement.type === "AC" ? 1150 : 620; const old = oldBase * (1 + Math.max(0, replacement.age - 5) * 0.035) * (replacement.inverter ? 0.8 : 1); const modern = replacement.type === "AC" ? 750 : 300; const save = (old - modern) * replacement.rate / 12; return { old, modern, save, payback: replacement.price / Math.max(save, 1) / 12 }; }, [replacement]);
  return <div className="space-y-6">
    <section className="bg-gradient-to-r from-amber-500 via-orange-500 to-rose-500 rounded-3xl p-8 text-white shadow-lg"><p className="text-amber-100 text-sm font-semibold uppercase tracking-wide">Financial and policy planning</p><h1 className="text-3xl font-bold mt-1">Energy Tools</h1><p className="mt-3 max-w-3xl text-amber-50">Check a bill, right-size your sanctioned load, plan time-of-day usage, assess replacement payback, and model rooftop solar. Tariffs are illustrative until an official DISCOM tariff is connected.</p></section>
    <div className="grid xl:grid-cols-2 gap-6">
      <Card title="Bill discrepancy checker" description="Prorates slab usage for long billing periods and checks entered FAC and duty."><div className="grid sm:grid-cols-3 gap-3"><NumberField label="Units" value={bill.units} onChange={(v)=>setBill({...bill,units:v})}/><NumberField label="Billing days" value={bill.days} onChange={(v)=>setBill({...bill,days:v})}/><NumberField label="Amount charged (₹)" value={bill.charged} onChange={(v)=>setBill({...bill,charged:v})}/><NumberField label="FAC ₹/unit" step="0.01" value={bill.fac} onChange={(v)=>setBill({...bill,fac:v})}/><NumberField label="Duty ₹/unit" step="0.01" value={bill.duty} onChange={(v)=>setBill({...bill,duty:v})}/></div><div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">Expected: <strong>{money(audit.expected)}</strong> · {audit.gap > 0 ? <span className="text-red-700">Potential excess: <strong>{money(audit.gap)}</strong></span> : <span className="text-emerald-700">No excess found from entered amounts</span>}<p className="text-xs text-gray-500 mt-2">For a formal complaint, verify rates against your current SERC tariff order before filing.</p></div>{audit.gap > 0 && <details className="mt-4 text-sm"><summary className="cursor-pointer font-semibold text-amber-700">View dispute-letter draft</summary><div className="mt-2 border rounded-xl p-4 text-gray-700 leading-6">Subject: Request for review of electricity bill<br/><br/>I request a review of my {bill.days}-day bill for {bill.units} units. Prorating the slab allowance to the billing period and adding the entered FAC and duty produces an estimated amount of {money(audit.expected)}, compared with {money(bill.charged)} charged. Please provide the tariff calculation and correct any discrepancy.<br/><button onClick={() => window.print()} className="mt-3 rounded-lg bg-gray-900 px-3 py-2 text-white">Print / Save as PDF</button></div></details>}</Card>
      <Card title="Sanctioned-load optimizer" description="Compare your contract load with historic peak demand."><div className="grid sm:grid-cols-3 gap-3"><NumberField label="Sanctioned load (kW)" value={load.sanctioned} onChange={(v)=>setLoad({...load,sanctioned:v})}/><NumberField label="Peak demand (kW)" value={load.peak} onChange={(v)=>setLoad({...load,peak:v})}/><NumberField label="Fixed charge ₹/kW" value={load.fixedRate} onChange={(v)=>setLoad({...load,fixedRate:v})}/></div><p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm">Suggested load: <strong>{Math.max(1, Math.ceil(load.peak + .5))} kW</strong>. Potential fixed-charge saving: <strong className="text-emerald-700">{money(loadSavings)}/month</strong>.</p></Card>
      <Card title="Time-of-Day load shifting" description="Move flexible loads such as EV charging, pumps, or laundry into solar hours."><div className="grid sm:grid-cols-3 gap-3"><NumberField label="Flexible units to shift/month" value={tod.flexible} onChange={(v)=>setTod({...tod,flexible:v})}/><NumberField label="Base rate ₹/unit" step="0.1" value={tod.rate} onChange={(v)=>setTod({...tod,rate:v})}/><NumberField label="Solar rebate ₹/unit" step="0.1" value={tod.rebate} onChange={(v)=>setTod({...tod,rebate:v})}/><NumberField label="Peak surcharge" step="0.01" value={tod.surcharge} onChange={(v)=>setTod({...tod,surcharge:v})}/></div><p className="mt-5 rounded-xl bg-indigo-50 p-4 text-sm">Shift {tod.flexible} units from 5–10 PM to 9 AM–5 PM to save about <strong className="text-indigo-700">{money(todSavings)}/month</strong>.</p></Card>
      <Card title="Appliance replacement payback" description="Models degradation from age and compares a modern efficient replacement."><div className="grid sm:grid-cols-3 gap-3"><label className="text-sm text-gray-600">Appliance<select className={input} value={replacement.type} onChange={(e)=>setReplacement({...replacement,type:e.target.value})}><option>AC</option><option>Fridge</option></select></label><NumberField label="Age (years)" value={replacement.age} onChange={(v)=>setReplacement({...replacement,age:v})}/><NumberField label="Replacement cost (₹)" value={replacement.price} onChange={(v)=>setReplacement({...replacement,price:v})}/><NumberField label="Electricity rate ₹/unit" value={replacement.rate} onChange={(v)=>setReplacement({...replacement,rate:v})}/></div><p className="mt-5 rounded-xl bg-rose-50 p-4 text-sm">Estimated old consumption: <strong>{Math.round(replacementResult.old)} kWh/year</strong> vs modern efficient model: <strong>{replacementResult.modern} kWh/year</strong>. Save <strong className="text-rose-700">{money(replacementResult.save)}/month</strong>; payback in <strong>{replacementResult.payback.toFixed(1)} years</strong>.</p></Card>
      <Card title="PM Surya Ghar rooftop solar" description="Estimate system size, central subsidy, net savings, and simple payback."><div className="grid sm:grid-cols-3 gap-3"><NumberField label="Monthly units" value={solar.units} onChange={(v)=>setSolar({...solar,units:v})}/><NumberField label="Usable roof (sq ft)" value={solar.roof} onChange={(v)=>setSolar({...solar,roof:v})}/><NumberField label="Electricity rate ₹/unit" value={solar.rate} onChange={(v)=>setSolar({...solar,rate:v})}/><NumberField label="Loan rate (%)" step="0.1" value={solar.loanRate} onChange={(v)=>setSolar({...solar,loanRate:v})}/></div><p className="mt-5 rounded-xl bg-teal-50 p-4 text-sm">Recommended: <strong>{solarResult.capacity} kW</strong> · estimated cost {money(solarResult.cost)} · assumed central subsidy <strong>{money(solarResult.subsidy)}</strong> · bill reduction <strong className="text-teal-700">{money(solarResult.monthly)}/month</strong> · simple payback <strong>{solarResult.payback} months</strong>.<br/><span className="text-xs text-gray-500">Net outlay {money(solarResult.netOutlay)}; indicative 5-year loan EMI at {solar.loanRate}%: {money(solarResult.emi)}/month. Subsidy and net-metering eligibility must be confirmed with your state portal/vendor.</span></p></Card>
      <section className="rounded-2xl border border-cyan-200 bg-cyan-50 p-6 flex flex-col justify-between"><div><h2 className="text-xl font-bold">Need AC or appliance-level numbers?</h2><p className="text-sm text-gray-600 mt-2">Use the dedicated thermal sizing advisor and virtual appliance audit matrix for a deeper estimate.</p></div><div className="flex gap-3 mt-5"><Link className="bg-cyan-700 text-white rounded-lg px-4 py-2 text-sm font-semibold" to="/ac-advisor">AC advisor</Link><Link className="bg-white border border-cyan-700 text-cyan-800 rounded-lg px-4 py-2 text-sm font-semibold" to="/ai-insights/audit-matrix">Audit matrix</Link></div></section>
    </div>
  </div>;
}
